// <auto-generated />
using System;
using Fretefy.Test.Infra.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Fretefy.Test.Infra.EntityFramework.Migrations
{
    [DbContext(typeof(TestDbContext))]
    [Migration("20250210224403_regiao-tabela")]
    partial class regiaotabela
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Fretefy.Test.Domain.Entities.Cidade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("UF")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cidade");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dec4198f-1961-46e5-a8a3-ad271819086d"),
                            Nome = "Rio Branco",
                            UF = "AC"
                        },
                        new
                        {
                            Id = new Guid("089c9fb8-0dad-4ec4-83d9-29ac6fc34b88"),
                            Nome = "Maceió",
                            UF = "AL"
                        },
                        new
                        {
                            Id = new Guid("feb67e6d-df26-4603-ab25-ab96638e65bd"),
                            Nome = "Macapá",
                            UF = "AP"
                        },
                        new
                        {
                            Id = new Guid("1f298eb3-aeca-4217-a9bc-b72be6e59a52"),
                            Nome = "Manaus",
                            UF = "AM"
                        },
                        new
                        {
                            Id = new Guid("e01b486a-0505-449d-b395-4699c0530124"),
                            Nome = "Salvador",
                            UF = "BA"
                        },
                        new
                        {
                            Id = new Guid("e387bb29-c97b-4dbd-8680-a99e84ba7a1d"),
                            Nome = "Fortaleza",
                            UF = " CE"
                        },
                        new
                        {
                            Id = new Guid("8009a797-9abb-4a60-abbf-238183ae5327"),
                            Nome = "Brasília",
                            UF = "DF"
                        },
                        new
                        {
                            Id = new Guid("de1c3447-6550-485b-b2f7-ac53f78e790d"),
                            Nome = "Vitória",
                            UF = "ES"
                        },
                        new
                        {
                            Id = new Guid("18bda21f-6af9-4f0a-8c16-4fc7fc134777"),
                            Nome = "Goiânia",
                            UF = "GO"
                        },
                        new
                        {
                            Id = new Guid("0334d8a1-3e05-47a1-a2f2-83e7c9673da2"),
                            Nome = "São Luís",
                            UF = "MA"
                        },
                        new
                        {
                            Id = new Guid("2057bccf-1975-4cc3-929c-0c11549d372e"),
                            Nome = "Cuiabá",
                            UF = "MT"
                        },
                        new
                        {
                            Id = new Guid("d3a4ef14-a808-4537-b138-6667b5df6e46"),
                            Nome = "Campo Grande",
                            UF = "MS"
                        },
                        new
                        {
                            Id = new Guid("db4d0f86-23fe-44f0-bcdc-1a524d364abd"),
                            Nome = "Belo Horizonte",
                            UF = "MG"
                        },
                        new
                        {
                            Id = new Guid("5a99bcac-ce2d-44b5-8f3f-d25b48dfff9c"),
                            Nome = "Belém",
                            UF = "PA"
                        },
                        new
                        {
                            Id = new Guid("971260e3-3f0d-49af-a8f5-bf3649d11c66"),
                            Nome = "João Pessoa",
                            UF = "PB"
                        },
                        new
                        {
                            Id = new Guid("bcbedb6b-4abb-467f-b15d-955c31d7fc81"),
                            Nome = "Curitiba",
                            UF = "PR"
                        },
                        new
                        {
                            Id = new Guid("a565a4b8-98ea-4434-ac79-10771a860980"),
                            Nome = "Recife",
                            UF = "PE"
                        },
                        new
                        {
                            Id = new Guid("fa14bf23-00a1-4b3f-a7e8-699d30e23a8c"),
                            Nome = "Teresina",
                            UF = "PI"
                        },
                        new
                        {
                            Id = new Guid("cd72e384-4566-4f1c-9696-7d47c5e1c2b5"),
                            Nome = "Rio de Janeiro",
                            UF = "RJ"
                        },
                        new
                        {
                            Id = new Guid("fcb3a392-0fd1-4bfc-8586-b32235610fed"),
                            Nome = "Natal",
                            UF = "RN"
                        },
                        new
                        {
                            Id = new Guid("36d9d738-019a-4237-b854-d3c8d741486f"),
                            Nome = "Porto Alegre",
                            UF = "RS"
                        },
                        new
                        {
                            Id = new Guid("b5b66aaa-0ffc-4ceb-b7a8-8054557835f3"),
                            Nome = "Porto Velho",
                            UF = "RO"
                        },
                        new
                        {
                            Id = new Guid("68bc6dee-67af-4d8e-aedc-20efc96371ca"),
                            Nome = "Boa Vista",
                            UF = "RR"
                        },
                        new
                        {
                            Id = new Guid("a8a71fd5-8f66-474e-95ca-9f4ddae414b9"),
                            Nome = "Florianópolis",
                            UF = "SC"
                        },
                        new
                        {
                            Id = new Guid("c6528d61-ea46-4c60-9460-843d7dbf5ddb"),
                            Nome = "São Paulo",
                            UF = "SP"
                        },
                        new
                        {
                            Id = new Guid("fd40ca33-f40d-46b4-88d2-64b232421950"),
                            Nome = "Aracaju",
                            UF = "SE"
                        },
                        new
                        {
                            Id = new Guid("9acfe167-1000-46dd-8c2d-68c59d7afa1f"),
                            Nome = "Palmas",
                            UF = "TO"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
